version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ims-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    env_file:
      - .env

  vite:
    image: node:18-alpine
    container_name: ims-vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: ["npm", "run", "dev"]
