version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=aws-0-us-east-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres.dntlbztppfuvhwfhoksf
      - DB_PASSWORD=Jobeix@@662.
      - DB_SSLMODE=require
    depends_on:
      - vite

  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-dev
    command: npm run dev
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
